// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// Deployed at https://nacekepa.work/ via GitHub Pages with a custom domain (public/CNAME).
// The site is one page (src/pages/index.astro) with in-page sections; old URLs redirect into it
// (old /portfolio/<slug> pages go straight to the matching project sheet, #p-<new-slug>).
export default defineConfig({
  site: 'https://nacekepa.work',
  trailingSlash: 'ignore',
  integrations: [sitemap({ filter: (page) => !/\/(services|portfolio|skills|about|order|sl|admin|news)(\/|$)/.test(new URL(page).pathname) })],
  // Never inline built scripts into the HTML: the Content-Security-Policy only trusts files from this site.
  vite: { build: { assetsInlineLimit: 0 } },
  redirects: {
    "/services": "/#services",
    "/portfolio": "/#work",
    "/skills": "/#skills",
    "/about": "/#about",
    "/order": "/#order",
    "/sl": "/#sl",
    "/sl/services": "/#sl-services",
    "/sl/portfolio": "/#sl-work",
    "/sl/skills": "/#sl-skills",
    "/sl/about": "/#sl-about",
    "/sl/order": "/#sl-order",
    "/portfolio/backpack-buckle": "/#p-engineered-backpack-buckle",
    "/sl/portfolio/backpack-buckle": "/#sl-p-engineered-backpack-buckle",
    "/portfolio/bike-light-bracket": "/#p-replacement-bike-light-bracket",
    "/sl/portfolio/bike-light-bracket": "/#sl-p-replacement-bike-light-bracket",
    "/portfolio/blind-cord-cleat": "/#p-childproof-blind-cord-cleat",
    "/sl/portfolio/blind-cord-cleat": "/#sl-p-childproof-blind-cord-cleat",
    "/portfolio/cable-clip": "/#p-snap-on-desk-cable-clip",
    "/sl/portfolio/cable-clip": "/#sl-p-snap-on-desk-cable-clip",
    "/portfolio/charger-strain-relief": "/#p-laptop-charger-strain-relief",
    "/sl/portfolio/charger-strain-relief": "/#sl-p-laptop-charger-strain-relief",
    "/portfolio/cocktail-dispenser": "/#p-automated-cocktail-dispenser",
    "/sl/portfolio/cocktail-dispenser": "/#sl-p-automated-cocktail-dispenser",
    "/portfolio/door-sensor-bot": "/#p-door-open-telegram-bot",
    "/sl/portfolio/door-sensor-bot": "/#sl-p-door-open-telegram-bot",
    "/portfolio/door-stopper-wedge": "/#p-adjustable-door-wedge",
    "/sl/portfolio/door-stopper-wedge": "/#sl-p-adjustable-door-wedge",
    "/portfolio/drawer-divider": "/#p-modular-drawer-divider-system",
    "/sl/portfolio/drawer-divider": "/#sl-p-modular-drawer-divider-system",
    "/portfolio/drill-bit-rack": "/#p-magnetic-back-drill-bit-rack",
    "/sl/portfolio/drill-bit-rack": "/#sl-p-magnetic-back-drill-bit-rack",
    "/portfolio/famfive": "/#p-famfive",
    "/sl/portfolio/famfive": "/#sl-p-famfive",
    "/portfolio/fridge-thermometer": "/#p-wi-fi-fridge-thermometer",
    "/sl/portfolio/fridge-thermometer": "/#sl-p-wi-fi-fridge-thermometer",
    "/portfolio/headphone-hook": "/#p-under-desk-headphone-hook",
    "/sl/portfolio/headphone-hook": "/#sl-p-under-desk-headphone-hook",
    "/portfolio/heatset-wall-anchor": "/#p-heat-set-insert-wall-anchor",
    "/sl/portfolio/heatset-wall-anchor": "/#sl-p-heat-set-insert-wall-anchor",
    "/portfolio/hose-adapter": "/#p-garden-hose-universal-adapter",
    "/sl/portfolio/hose-adapter": "/#sl-p-garden-hose-universal-adapter",
    "/portfolio/laptop-riser": "/#p-ergonomic-laptop-riser",
    "/sl/portfolio/laptop-riser": "/#sl-p-ergonomic-laptop-riser",
    "/portfolio/magnetic-cable-holder": "/#p-magnetic-desk-cable-holder",
    "/sl/portfolio/magnetic-cable-holder": "/#sl-p-magnetic-desk-cable-holder",
    "/portfolio/phone-wall-dock": "/#p-bedside-phone-wall-dock",
    "/sl/portfolio/phone-wall-dock": "/#sl-p-bedside-phone-wall-dock",
    "/portfolio/plant-moisture-monitor": "/#p-plant-moisture-monitor",
    "/sl/portfolio/plant-moisture-monitor": "/#sl-p-plant-moisture-monitor",
    "/portfolio/rfid-drawer-lock": "/#p-rfid-drawer-lock",
    "/sl/portfolio/rfid-drawer-lock": "/#sl-p-rfid-drawer-lock",
    "/portfolio/scooter-grip-tpu": "/#p-tpu-scooter-handlebar-grip",
    "/sl/portfolio/scooter-grip-tpu": "/#sl-p-tpu-scooter-handlebar-grip",
    "/portfolio/screwdriver-rack": "/#p-wall-mount-screwdriver-rack",
    "/sl/portfolio/screwdriver-rack": "/#sl-p-wall-mount-screwdriver-rack",
    "/portfolio/shelf-bracket": "/#p-reinforced-shelf-bracket",
    "/sl/portfolio/shelf-bracket": "/#sl-p-reinforced-shelf-bracket",
    "/portfolio/smart-pet-feeder": "/#p-scheduled-pet-feeder",
    "/sl/portfolio/smart-pet-feeder": "/#sl-p-scheduled-pet-feeder",
    "/portfolio/tablet-stand": "/#p-adjustable-tablet-stand",
    "/sl/portfolio/tablet-stand": "/#sl-p-adjustable-tablet-stand",
    "/portfolio/tripod-qr-plate": "/#p-arca-swiss-quick-release-plate",
    "/sl/portfolio/tripod-qr-plate": "/#sl-p-arca-swiss-quick-release-plate",
    "/portfolio/vacuum-hose-adapter": "/#p-universal-vacuum-hose-adapter",
    "/sl/portfolio/vacuum-hose-adapter": "/#sl-p-universal-vacuum-hose-adapter",
    "/portfolio/washing-machine-knob": "/#p-replacement-washing-machine-knob",
    "/sl/portfolio/washing-machine-knob": "/#sl-p-replacement-washing-machine-knob",
    "/portfolio/whistle-440hz": "/#p-440-hz-precision-whistle",
    "/sl/portfolio/whistle-440hz": "/#sl-p-440-hz-precision-whistle"
  }
});
